/**
 * Australian Vaccine Codes (urn:oid:1.2.36.1.2001.1005.17)
 *
 * These codes defined in the Australian Childhood Immunisation Register Vaccine,
 * are managed and published by the Australian Department of Health and Ageing.
 * The version of the code system should be conveyed along with the code, and
 * the version should be in the form YYYYMM which corresponds to the official
 * month of the medicare schedule that the code is taken from.
 *
 * In FHIR, these codes are included in the R4 vaccine codes value set:
 * https://www.hl7.org/fhir/R4/valueset-vaccine-code.html
 *
 * @see https://developer.digitalhealth.gov.au/resources/australian-digital-health-agency-adha-oid-repository
 */
export const AustralianVaccineCodes: string[] = [
    "AGRPAL",
    "AVAXM",
    "BCG",
    "CDT",
    "CMX",
    "DTP",
    "DTPA",
    "ENGP",
    "FLRIX",
    "FLUVAX",
    "FLVRN",
    "FVXJNR",
    "GNDIP",
    "GNFLU",
    "GNHEP",
    "GNHIB",
    "GNHPA",
    "GNJEN",
    "GNMEA",
    "GNMEN",
    "GNMUM",
    "GNPNE",
    "GNPOL",
    "GNROX",
    "GNRUB",
    "GNTET",
    "GNVAR",
    "HATWNJ",
    "HAVAQ",
    "HAVJ",
    "HBOC",
    "HBV",
    "HBVP",
    "HBX",
    "IFHX",
    "IFIP",
    "IFPA",
    "IFX",
    "IFXB",
    "INFLUV",
    "IPV",
    "JEVAX",
    "MENJUG",
    "MENTEC",
    "MENUME",
    "MENVAX",
    "MMR",
    "MMRCSL",
    "MMRSKB",
    "MNTRX",
    "NEISVC",
    "OPV",
    "P",
    "PANVAX",
    "PDCL",
    "PLCL",
    "PNEUMO",
    "PRPD",
    "PROQAD",
    "PRPOMP",
    "PRPT",
    "PRVNR",
    "PRVTH",
    "PRXTEX",
    "QDCL",
    "ROTRIX",
    "ROTTEQ",
    "SYNFLX",
    "TCL",
    "VAXGRP",
    "VGRJNR",
    "VLRIX",
    "VRVAX",
];
